jewllery/cart/urls.py
from . import views
from django.urls import path, include
app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/',views.add_cart, name='add_cart'),
    path('', views.cart_details, name='cart_details'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('remove_all/<int:product_id>/', views.remove_all, name='remove_all')

]

jewllery/jewllery/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jewls', include('jewls.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

jewllery/jewls/urls.py
from django.urls import path
from jewls import views
app_name = 'jewls'

urlpatterns = [
    path('', views.allProductCategory, name='allProductCategory'),
    path('<slug:c_slug>/', views.allProductCategory, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.productDetails, name='productCateDetail'),

]

jewllery/search/urls.py
from . import views
from django.urls import path, include
app_name = 'search'

urlpatterns = [
    path('', views.searchResult, name='searchResult'),
]

jewllery/cart/models.py
from django.db import models
from jewls.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

jewllery/jewls/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=300, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('jewls:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)
class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=300, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    def get_url(self):
        return reverse('jewls:productCateDetail', args=[self.category.slug, self.slug])

    class Meta:
        ordering = ['name']
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

jewllery/search/models.py
from django.db import models

# Create your models here.

jewllery/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from jewls .models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request,product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save(),
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()

    return redirect('cart:cart_details')

def cart_details(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))
def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id =_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_details')
def remove_all(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_details')

jewllery/jewls/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from . models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage


# Create your views here.
def allProductCategory(request, c_slug=None):
    c_page = None
    products_list = None
    # products = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)
    return render(request, 'category.html', {'category': c_page, 'products': products})
def productDetails(request,c_slug,product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

jewllery/search/views.py
from django.shortcuts import render
from jewls.models import Product
from django.db.models import Q

# Create your views here.
def searchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request, 'search.html', {'query': query, 'products': products})

jewllery/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/custom.css'%}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <script src=" https://kit.fontawesome.com/fc51e437b8.js " crossorigin="anonymous"></script>
    <title>{% block title %} {% endblock %}</title>
</head>
<body class="d-flex flex-column min-vh-100">
    <div class="container">
        {% include 'header.html' %}
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}
    </div>
    {% include 'footer.html' %}
        <script src="{% static 'js/popper.min.js' %}" ></script>
        <script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

jewllery/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    This is the Cart Page. Proceed to review your items and place the order.
{% endblock %}

{% block title %}
    Cart - LICERIA & CO Gold& Diamonds
{% endblock %}

{% block content %}
    {% if not cart_items %}
        <div class="text-center">
            <br>
            <h1 class="text-center">
                Your shopping cart is EMPTY
            </h1>
            <br>
            <p class="text-center">Please Click <a href="{% url 'jewls:allProductCategory' %}">Here</a>to continue shopping.</p>
        </div>
    {% else %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center">
                    Your Shopping Cart
                </h1>
                <br>
            </div>
        </div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table custom_table">
                <thead class="custom_head">
                    <tr>
                        <th colspan="5">
                            Your Items
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for cart_item in cart_items %}
                        <tr>
                            <td>
                                <a href="{{cart_item.product.get_url}}">
                                    <img src="{{ cart_item.product.image.url}}" alt="" class="float-left rounded custom_img" width="100px" height="120px">
                                </a>
                            </td>
                            <td class="text-left">
                                {{cart_item.product.name}}
                                <br>
                                SKU : {{cart_item.product.id}}
                                <br>
                                Price: $ {{cart_item.product.price}}
                                <br>
                                Qty : {{cart_item.quantity}} X  $ {{cart.item}}
                            </td>
                            <td>
                                $ {{cart_item.sub_total}}
                            </td>
                            {% if cart_item.quantity < cart_item.product.stock %}
                                <td>
                                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a">
                                        <i class="fa fa-plus custom_icon" ></i>
                                    </a>
                                     &nbsp;
                                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a">
                                        <i class="fa fa-minus" ></i>
                                    </a>
                                    &nbsp;
                                    <a href="{% url 'cart:remove_all' cart_item.product.id %}" class="custom_a" >
                                         <i class="fa fa-trash" ></i>
                                    </a>
                                </td>
                            {% else %}
                                 <td>&nbsp;
                                    <a href="{% url 'cart:add_cart' cart_item.product.id" class="custom_a">
                                        <i class="fa fa-plus custom_icon" ></i>
                                    </a>
                                     &nbsp;
                                     <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a">
                                           <i class="fa fa-minus" ></i>
                                    </a>
                                    &nbsp;
                                    <a href="{% url 'cart:remove_all' cart_item.product.id %}" class="custom_a" >
                                         <i class="fa fa-trash" ></i>
                                    </a>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="text-center col-12 col-sm-12 col-md-12 col-lg-6">
            <table class="table custom_table">
                <thead class="custom_head">
                    <tr>
                        <th>
                            Checkout
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            Please review your shopping cart items before proceeding with the order payment...
                        </td>
                    </tr>
                    <tr>
                        <td class="text-left">
                            Your Total is : <strong>{{total}}</strong>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="mx-auto">
                <a href="{% url 'jewls:allProductCategory' %}" class="btn btn-success btn-block mt-5 custom_btn">Continue Shopping</a>
                <a href="{% url 'jewls:allProductCategory' %}" class="btn btn-info btn-block mt-5 custom_btn">Payment</a>
            </div>
        </div>
    </div>
    {% endif %}

{% endblock %}

jewllery/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {% if category %}
        {{ category.description | truncatewords:155 }}
    {% else %}
        Welcome to LICERIA & CO, where you can buy different models as per your choice...
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{ category.name }} - LICERIA & CO
    {% else %}
        See Our New Collections - LICERIA & CO
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
        <div>
            <div class="row my_row">
                <div class="mx_auto">
                    <p><a href="{% url 'jewls:allProductCategory' %}">Our Product Collections</a></p>
                </div>
            </div>
        </div>
    {% endif %}
    <div class="mx_auto">
        {% if category %}
            <img  class="my_img" src="{{ category.image.url }}" alt="{{ category.name }}" width="70%" height="800px">
    </div>
    <br>
    <div>
        <h1 class="text-center my_title">{{ category.name }}</h1>
        <p class="text-justify-center">{{ category.description }}</p>
    </div>
        {% else %}
            <div>
                <img class="my_img"  src="{% static 'img/banner.png' %}" alt="Our Products" width="1300px" height="600px" >
            </div>
            <br>
            <div class="mb-5">
                <h1 class="text-center p-5 my_title">Our Product Collections</h1>
                <p class="text-justify-center">Bringing jewelry designs to life is a skill in and of itself,
                    and one that can vary greatly depending on the type of bauble you want to produce.
                    Some types of jewelry can be created by hand. Beaded or clay pieces, for example,
                    are more beginner-friendly options that don’t require too many tools or specialized skills.
                    With just a little experimentation—or a few classes—you can learn techniques to produce these
                    types of accessories. </p>
            </div>
        {% endif %}
    <div class="container ">
        <div class="row mx_auto">
            {% for product in products.object_list %}
                <div class="mb-5 col-9 col-sm-12 col-md-4 col-lg-4">
                    <div class="card text-center" style="min-width:18rem; height:750px;">
                        <a href="{{ product.get_url }}"> <img class="card-img-top my_img" src="{{ product.image.url }}" alt="{{ product.name }}" height="500px" width="400px" ></a>
                        <div class="card-body">
                            <h4 class="card-title">{{ product.name }}</h4>
                            <h5 class="card-text">{{ product.description }}</h5>
                            <p class="card-text">{{ product.price }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="mx_auto">
            {% if products.paginator.num_pages > 1 %}

            <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                    <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %} " >{{pg}}</a>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <br>
    </div>
{% endblock %}

jewllery/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer mt-auto">
  <p class="text-center">&copy;  LICERIA & CO ,  All rights reserved</p>
</div>

jewllery/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'jewls:allProductCategory' %}">
            <img src="{% static 'img/logo.png' %}" alt="logo" width="130px" height="130px" style="border-radius:50%;">
        </a>
    </center>
</header>

jewllery/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">LICERIA & CO</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Shop</a>
        </li>
        <li class="nav-item dropdown {% if 'jewls' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="{% url 'jewls:allProductCategory' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           All Products
          </a>
          <ul class="dropdown-menu">
              {% for i in links %}
                <li><a class="dropdown-item" href="{{ i.get_url }}">{{ i.name }}</a></li>
              {% endfor %}
              </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:cart_details' %}"><i class="fa fa-shopping-cart" ></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" role="search" action="{% url 'search:searchResult' %}" method="GET">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

jewllery/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {{ product.description|truncatewords:155 }}
{% endblock %}

{% block title %}
    {% if category %}
        {{ product.name }}
    {% endif %}
{% endblock %}

{% block content %}
    <div  class="row my_Product_row">
        <div class="mx_auto">
            <p>
                <a href="{% url 'jewls:allProductCategory' %}">Home</a> |
                <a href="{{ product.category.get_url }}">{{ product.category}}</a>
                {{product.name}}
            </p>
        </div>
    </div>
    <div class="container ">
        <br>
        <div class="row mb-5">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div class="" style="min-width:18rem;">
                    <img src="{{ product.image.url }}" alt="{{ product.name }}" width="400px" height="400px">
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 ">
                <div>
                    <h1 class="">{{ product.name }}</h1>
                    <p>${{ product.price }}</p>
                    <p class="text-uppercase">Product Description</p>
                    <p class="text-justify ">{{ product.description }}</p>
                    {% if product.stock <= 0 %}
                        <p class="font-weight-bold"><b>Out of Stock</b></p>
                    {% else %}
                        <a href="{% url 'cart:add_cart' product.id %}" class="btn btn-primary">Add to Cart</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

jewllery/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    We have variety of products .
{% endblock %}

{% block title %}
   Search
{% endblock %}

{% block content %}
    <div>
        <p class="text-center my_search">You have searched for : <b>"{{query}}"</b></p>
    </div>
    <div class="container ">
        <div class="row mx_auto">
            {% for product in products %}
                <div class="mb-5 col-9 col-sm-12 col-md-4 col-lg-4">
                    <div class="card text-center" style="min-width:18rem; height:750px;">
                        <a href="{{ product.get_url }}"> <img class="card-img-top my_img" src="{{ product.image.url }}" alt="{{ product.name }}" ></a>
                        <div class="card-body">
                            <h4 class="card-title">{{ product.name }}</h4>
                            <h5 class="card-text">{{ product.description }}</h5>
                            <p class="card-text">{{ product.price }}</p>
                        </div>
                    </div>
                </div>
            {% empty %}
        </div>
        <div class="row mx_auto">
            <p class="text-center my_search">No Results Found</p>
        </div>
            {% endfor %}
    </div>
{% endblock %}